-- begin JNJREPOSITORY_STAGING
create unique index IDX_JNJREPOSITORY_STAGING_UNIQ_API on JNJREPOSITORY_STAGING (API)^
-- end JNJREPOSITORY_STAGING
-- begin JNJREPOSITORY_MAIN
create unique index IDX_JNJREPOSITORY_MAIN_UNIQ_DEPARTMENT on JNJREPOSITORY_MAIN (DEPARTMENT)^
create unique index IDX_JNJREPOSITORY_MAIN_UNIQ_API on JNJREPOSITORY_MAIN (API)^
-- end JNJREPOSITORY_MAIN
